stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - dataset
    - src/prepare.py
    outs:
    - output/prepared_data.pkl

  train:
    cmd: python src/train.py output/prepared_data.pkl
    deps:
    - output/prepared_data.pkl
    - src/train.py
    - dataset
    outs:
    - output/models/KRR_model.pkl
    - output/plots/Learning_Curve.png
    metrics:
    - output/metrics.csv:
        cache: false
    params:
    - train.metric
    - train.order
    - train.sigma
  
  test:
    cmd: python src/test.py output/dataset
    deps: 
    - output/dataset
    - src/test.py
    outs:
    - output/test/actual_pred
    metrics:
    - output/test/live/metrics.json:
        cache: false

plots:
  - APTrain:
      template: linear
      title: Actual - Pred - Train
      x_label: Molecule
      y_label: Energy
      x: molecule
      y:
        output/test/actual_pred/train.json: "actual"
        # output/test/actual_pred/train.json: "predicted"
  - APTest:
      template: linear
      title: Actual - Pred - Test
      x_label: Molecule
      y_label: Energy
      x: molecule
      y:
        output/test/actual_pred/test.json: "actual"
        # output/test/actual_pred/test.json: "predicted"
  - CSV:
      template: scatter
      title: Metrics
      # file: output/metrics.csv
      x: sigma
      y:
        output/metrics.csv: MAE
      x_label: Sigma
      y_label: MAE Value
  - output/plots/Learning_Curve.png

