stages:
  train:
    cmd: python src/train_KRR.py
    deps:
    - dataset/
    - src/train_KRR.py
    outs:
    - output/model/KRR_model.pkl
    - output/plots/Learning_Curve.png
    metrics:
    - output/metrics.csv:
        cache: false
